site_name: MZY Blog

theme:
  name: material
  custom_dir: overrides
  language: zh
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette: 
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        name: Switch to light mode
        icon: material/brightness-7
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        name: Switch to dark mode
        icon: material/brightness-4
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.follow
    # - header.autohide
    # - content.action.edit
    # - content.action.view

repo_url: https://github.com/Alexair059/Alexair059.github.io
repo_name: Alexair059.github.io

edit_uri: edit/main/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Alexair059
      name: My Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:alexair059@gmail.com
      name: My Email

copyright: Copyright &copy; 2020 - 2023 Alexair
    

nav:
  - Home: index.md
  - AI:
      - SLIC Pixelation: ai/ch2_1.md
      - 变分自编码器|VAE: ai/ch5_1.md
      - 朴素贝叶斯: ai/ch1_4.md
      - 感知机: ai/ch1_2.md
      - SVM(未完成): ai/ch1_7.md
  - Web:
      # - 网络服务:
      - Nginx: web/ch1.md
      - uWSGI: web/ch2.md
          # - TencentCloud: web/todo.md
      # - 后端:
      #     - Flask: web/todo3.md
      # - 前端:
      #     - Vue2&3: web/todo4.md
  - CTF:
      - 乱数假文&LSB隐写: ctf/ch1.md
      - FGSM攻击: ctf/ch2.md
  - Others:
      - Blog搭建: others/blog.md
      - mkdocs加密: others/mkdocs_encrypt.md
      - 琐碎: others/time.md

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/custom.css

plugins:
  - search: {}
  - encryptcontent: 
      title_prefix: '[限制]'
      summary: '[该内容已被加密保护]'
      encryption_info_message: '联系博主以获得权限'
      placeholder: 'Password'
      decryption_failure_message: '密码错误'
      # password_button: True
      # password_button_text: 'unlock'
      input_class: input-form
      # button_class: confirm-button
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
